### ISSUE TITLE
[Help Wanted] - Android && libcaesium

### ISSUE THREAD

**Issue by ferencIOS** [Lymphatus/libcaesium#16]
I am trying to compile the lib for Android on MacOS Ventura 13.3.1 - Apple M1.

My idea is to follow the [Android Guide](https://developer.android.com/studio/projects/add-native-code), starting from .a files or .java/c files.

First of all I changed the `Cargo.toml` file:
```
[...]
[lib]
[...]
crate-type = ["staticlib"]
[...]
```

Then:
```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup target add aarch64-linux-android
cargo build --release --target aarch64-linux-android
```

Result:
```bash
  Compiling libdeflate-sys v0.11.0
   Compiling libwebp-sys v0.4.2
   Compiling gifsicle v1.93.0
   Compiling mozjpeg-sys v1.0.6
   Compiling itertools v0.10.5
   Compiling filetime v0.2.21
   Compiling miniz_oxide v0.5.4
   Compiling wild v2.1.0
   Compiling arrayvec v0.7.2
error: failed to run custom build command for `mozjpeg-sys v1.0.6`

Caused by:
  process didn't exit successfully: `[path]/libcaesium/target/release/build/mozjpeg-sys-a12e86570479e512/build-script-build` (exit status: 1)
[...]
```

Thanks for your help!

**Comment by Lymphatus** [comment]
Unfortunately the process is a bit more complicated than that.
I know for sure it works because I successfully compiled the project for Android and built a demo app on top of it. I don't have an Apple Silicon (just an Intel one) but I remember I managed to get it working following this https://github.com/mozilla/rust-android-gradle

If I remember correctly I had to adjust a few things, but that was a good start. Mine was just an experiment and I did not go any further than building a simple app using the library, but I can get back to the code if you need further assistance.

Just keep in mind that the library is designed to accept an input file path and to write the compressed file into an output path, which is not really well suited for the Android environment due to OS permissions.

**Comment by ferencIOS** [comment]
Oh thanks! I will try to follow the guide.

If it should be simple I will write the steps that maybe it will be useful to someone else.

**Comment by ferencIOS** [comment]
Hi!

Starting from the `main` branch here is a [patch](https://github.com/Lymphatus/libcaesium/files/11562132/android.patch) for android support.

**STEPS**

- modified libcaesium sources as shown in the patch (`android-exp` branch was an inspiration)
- followed the instructions of `rust-android-gradle` chapter `Usage` as you suggested - [rust](https://github.com/mozilla/rust-android-gradle/tree/master#usage)
- added the `CaesiumNative.kt` into `caesium` package with a `compress` fun (as the rust signature `Java_com_example_caesium4android_caesium_CaesiumNative_compress` says)

```kotlin
package com.example.caesium4android.caesium

import java.lang.System.*

class CaesiumNative {

    external fun compress(source: String, destination: String): Boolean

    companion object {
        init {
            loadLibrary("caesium")
        }
    }
}
```

**Comment by Lymphatus** [comment]
Thanks! This is very similar to what I got during my experiments.
I think it's better to have a separate project like `libcaesium-android` to keep this repository as clean as possible. I've done something similar with https://github.com/Lymphatus/libcaesium-php for PHP.
I'll try in the next days.
